[package]
name = "rstd"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["staticlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.8"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'